[build]
  command = "pip install -r requirements.txt"
  publish = "build" # Ou o diretório onde seus arquivos estáticos, se houver, seriam publicados

[functions]
  # Esta seção 'functions' pode estar vazia ou conter outras configurações
  # MAS NÃO o 'python_version = "3.12"' diretamente aqui.

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app" # Onde 'app' é o nome do seu arquivo principal (ex: app.py) sem a extensão
  status = 200
