[build]
  command = "mkdir -p build && pip install -r requirements.txt"
  publish = "build" # Continua apontando para 'build'

[functions]
  # Esta seção 'functions' pode estar vazia ou conter outras configurações
  # MAS NÃO o 'python_version = "3.12"' diretamente aqui.

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app" # Onde 'app' é o nome do seu arquivo principal (ex: app.py) sem a extensão
  status = 200
